---
sidebar: sidebar
permalink: proxmox/proxmox-ontap.html
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff
summary: "Provision ONTAP storage for Proxmox Virtual Environment (VE) using NAS protocols (NFS, SMB) and SAN protocols (FC, iSCSI, NVMe). Select the appropriate protocol-specific procedure to configure shared storage for your Proxmox VE cluster."
---
= Learn about storage protocols for Proxmox VE with NetApp ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Provision ONTAP storage for Proxmox Virtual Environment (VE) using NAS protocols (NFS, SMB) and SAN protocols (FC, iSCSI, NVMe). Select the appropriate protocol-specific procedure to configure shared storage for your Proxmox VE cluster.

Ensure Proxmox VE hosts have FC, Ethernet, or other supported interfaces cabled to switches with communication to ONTAP logical interfaces. Always check the https://mysupport.netapp.com/matrix/#welcome[Interoperability Matrix Tool] for supported configurations. Example scenarios are created with assumption that two high speed network interface cards are available on each Proxmox VE host which are connected together to create bonded interfaces for fault tolerance and performance. Same uplink connections are used for all network traffic including host management, VM/container traffic, and storage access. When more network interfaces are available, consider separating storage traffic from other types of traffic.

For information about ONTAP storage architecture and supported storage types, see link:proxmox-ontap-architecture.html[Learn about ONTAP storage architecture for Proxmox VE] and link:proxmox-storage-types.html[Learn about supported storage types for Proxmox VE]. 

NOTE: When using LVM with SAN protocols (FC, iSCSI, NVMe-oF), the volume group can contain multiple LUNs or NVMe namespaces. In that case, all the LUNs or namespaces must be part of same consistency group to ensure data integrity. We don't support volume group that spans multiple ONTAP SVMs. Each volume group must be created from LUNs or namespaces from the same SVM.

== Choose a storage protocol

Select the protocol that matches your environment and requirements:

* link:proxmox-ontap-smb.html[Configure SMB/CIFS storage] - Configure SMB/CIFS file shares for Proxmox VE with multichannel support for fault tolerance and enhanced performance over multiple network connections.

* link:proxmox-ontap-nfs.html[Configure NFS storage] - Configure NFS storage for Proxmox VE with nConnect or session trunking for fault tolerance and performance enhancements using multiple network connections.

* link:proxmox-ontap-fc.html[Configure LVM with FC] - Configure Logical Volume Manager (LVM) with Fibre Channel for high-performance, low-latency block storage access across Proxmox VE hosts.

* link:proxmox-ontap-iscsi.html[Configure LVM with iSCSI] - Configure Logical Volume Manager (LVM) with iSCSI for block storage access over standard Ethernet networks with multipath support.

* link:proxmox-ontap-nvme-fc.html[Configure LVM with NVMe/FC] - Configure Logical Volume Manager (LVM) with NVMe over Fibre Channel for high-performance block storage using the modern NVMe protocol.

* link:proxmox-ontap-nvme-tcp.html[Configure LVM with NVMe/TCP] - Configure Logical Volume Manager (LVM) with NVMe over TCP for high-performance block storage over standard Ethernet networks using the modern NVMe protocol.

