---
sidebar: sidebar
permalink: vmware/vmw-vcf-protect-vmsc.html
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster
summary: 
---
= Learn about integrating ONTAP high availability with VMware vSphere Metro Storage Cluster (vMSC)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the NetApp solutions you can use to integrate NetApp ONTAP high availability with VMware vSphere Metro Storage Cluster (vMSC). This provides a robust solutions for VMware Cloud Foundation (VCF) management and workload domains.

This combination ensures continuous data availability, seamless failover, and disaster recovery across geographically dispersed sites, enhancing resilience and operational continuity for critical workloads. SnapMirror active sync (SAN and NAS), enables business services to continue operating even through a complete site failure, supporting applications to fail over transparently using a secondary copy. There is no manual intervention or custom scripting required to trigger a failover with SnapMirror active sync (SAN and NAS). A ONTAP mediator is used to monitor the health of the primary site and automatically failover to the secondary site in case of a disaster. The ONTAP mediator is deployed on a separate server or virtual machine that is not part of either site, ensuring the quorum is available to avoid split brain scenario.

Please refer to the following solutions for more details.

* link:vmw-vcf-vmsc-mgmt-smas.html[Stretch Cluster for Management Domain using SnapMirror active sync (SAN and NAS)]

* link:vmw-vcf-vmsc-mgmt-mcc.html[Stretch Cluster for Management Domain using MetroCluster]

* link:vmw-vcf-vmsc-viwld-smas.html[Stretch Cluster for Workload Domain using SnapMirror active sync (SAN and NAS)]

* link:vmw-vcf-vmsc-viwld-mcc.html[Stretch Cluster for Workload Domain using MetroCluster]
