---
sidebar: sidebar
permalink: vmware/vmw-vcf-mgmt-fc-requirements.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, aff, all-flash, fc, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10
summary: Requirements for converting vCenter server instances to VCF management domains using Fibre Channel datastores.
---
= Deployment requirements for converting vCenter server instances to VCF management domains with Fibre Channel datastores
:icons: font
:imagesdir: ../media/

[.lead]
Review the requirements for converting a vSphere 8 cluster with NetApp ONTAP FC datastores to a VMware Cloud Foundation management domain. The conversion process requires an AFF or ASA storage system, properly configured SVMs and LIFs for FC traffic, FC zoning on switches, a vSphere 8 cluster with ESXi hosts and vCenter, and dedicated network segments for vMotion.

== Infrastructure requirements
Make sure the following components and configurations are in place.

* NetApp ASA R2/ASA/AFF storage system with a storage virtual machine (SVM) configured to allow Fibre Channel (FC) traffic.
* Logical interface (LIF) created to carry FC traffic and is associated with the SVM.
* FC zoning configured on the switches designated to carry FC traffic.
* A vSphere 8 cluster with 4 x ESXi hosts and a vCenter appliance colocated on the cluster.
* Distributed port group configured for vMotion on the VLANs or network segments established for this purpose.
* Downloaded software required for the VCF conversion. For required software, go to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/download-software-for-converting-or-importing-existing-vsphere-environments-admin.html[Download Software for Converting or Importing Existing vSphere Environments].
* Prerequisites for ONTAP tools are met.
+
For complete information on prerequisites for ONTAP tools refer to https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements[Prerequisites for ONTAP tools for VMware vSphere deployment].
+
ONTAP tools for VMware vSphere 10 can be installed in either HA or non-HA configurations.

== Additional resources
* For supported storage and other considerations for converting or importing vSphere to VCF 5.2, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/considerations-before-converting-or-importing-existing-vsphere-environments-into-vcf-admin.html[Considerations Before Converting or Importing Existing vSphere Environments into VMware Cloud Foundation].

* For information on configuring ONTAP storage systems, refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 documentation].
* For information on configuring VCF, refer to the link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html[VMware Cloud Foundation 5.2 documentation].

== What's next?
After you reviewed the deployment requirements, link:vmw-vcf-mgmt-fc-deploy.html[deploy ONTAP tools and provision the FC datastore].
