---
sidebar: sidebar
permalink: vmware/vmw-vcf-disaster-recovery.html
keywords: vmware, vcf, dr, disaster recovery
summary: 
---

= Learn about protecting VMware datastores using NetApp Disaster Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the NetApp solutions for disaster recovery using NetApp Disaster Recovery for VMware. This provides for robust solutions for disaster recovery using block-level replication from a primary site to a disaster recovery site. 

NetApp Disaster Recovery is an effective and economical method to safeguard workloads against site failures and data integrity issues, including ransomware attacks. Furthermore, NetApp Disaster Recovery enhances this strategy by providing a managed, cloud-based disaster recovery solution, ensuring swift recovery and minimal downtime during disasters.

Please refer to the following solutions for the technical details.

* link:vmw-disaster-recovery-vmfs.html[DR using NetApp Disaster Recovery for VMFS Datastores]

* link:vmw-disaster-recovery-nfs.html[DR using NetApp Disaster Recovery for NFS Datastores]
  

// NetApp Solutions restructuring (jul 2025) - renamed from vmware/vmw-vcf-draas-bxp.adoc
