---
sidebar: sidebar
permalink: vmware/vmw-vcf-mgmt-principal-fc.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc
summary:
---
= Use an FC-based VMFS datastore on ONTAP as principal storage for VCF management domain
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this use case we outline the procedure to create a FC-based VMFS datastore on ONTAP as the primary storage for VMware Cloud Foundation (VCF) management domain. This procedure summarizes the required components, configurations, and deployment steps.

== Introduction

Where appropriate we will refer to external documentation for the steps that must be performed in vCenter, and reference those steps that are specific to the storage configuration portion.

For information on converting an existing VMFS datastore (includes iSCSI and NVMe-oF) in vSphere environment with ONTAP, refer to link:vmw-vcf-mgmt-vmfs.html[Converge vSphere Environment (VMFS datastore) to VCF Management Domain].

[NOTE]
VCF release 5.2 introduced the the capability to convert an existing vSphere 8 environment to a VCF management domain or import as VCF VI workload domains. Prior to this release, VMware vSAN was the only option for principal storage for the VCF management domain. NSX controller VMs are better to deploy on FC-based VMFS datastore or use dual network switch to avoid single point of failure. If those options are not available, consider using vSAN to host those VMs.

[NOTE]
This solution is applicable for ONTAP platforms supporting FC storage including NetApp ASA, AFF and FAS. 

== Prerequisites

The following components and configurations are used in this scenario:

* NetApp storage system with a storage virtual machine (SVM) configured to allow FC traffic.
* Logical interfaces (LIF) have been created on the FC fabric that is to carry FC traffic and is associated with the SVM.
* Zoning has been configured to use single initiator-target zoning on FC switches for host HBAs and storage targets.

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html[VMware Cloud Foundation Documentation].

== Deployment Steps

=== Management Domain - Default Cluster

VCF Installer tool supports VMFS on FC, NFS v3, and vSAN datastores for the management domain. The following steps outline the procedure to deploy a management domain with an FC-based VMFS datastore on ONTAP as the principal storage.

For more information on using an existing vSphere environment, refer to link:vmw-vcf-mgmt-vmfs.html[Converge vSphere Environment (VMFS datastore) to VCF Management Domain].

=== Management Domain - Additional Cluster

To Expand the management domain with an additional cluster, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html[Add an SDDC Cluster to a VCF Domain].

On High-level, the steps to add an additional cluster to the management domain are as follows:
* Ensure the hosts are commissioned and network pools are configured in vCenter.
* LUN is provisioned on the ONTAP storage system and presented to the hosts in the additional cluster.
* Create new SDDC Cluster creation on the Management Domain on vCenter and follow the wizard to add the additional cluster to the management domain.

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html[VMware Cloud Foundation Documentation].


