---
sidebar: sidebar
permalink: vmware/vmw-vcf-expand.html
keywords: vmware, vcf, expand, supplemental, storage
summary: "VMware Cloud Foundation (VCF) supports a wide range of supplemental storage options to expand storage on VCF management domains and Virtual Infrastructure (VI) workload domains."
---
= Learn about expanding storage for a VCF environment using supplemental storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
VMware Cloud Foundation (VCF) supports a wide range of supplemental storage options to expand storage on VCF management domains and Virtual Infrastructure (VI) workload domains.

NetApp's ONTAP tools for VMware vSphere provide an efficient solution for this expansion by integrating NetApp storage seamlessly into the VCF environment. 

ONTAP tools simplifies the setup and management of datastores, allowing administrators to provision and manage storage directly from the vSphere Client. ONTAP's advanced features, such as snapshots, cloning, and data protection, enhance storage performance, efficiency, and scalability within the VCF environment.

== Supported protocols for expanding storage

VCF environments can be expanded using several storage protocols, each offering unique benefits and use cases. 

You can use the following protocols to expand storage in VCF management domains and VI workload domains. Choose the best option for your environment to seamlessly integrate supplemental storage into your VCF deployment.

.iSCSI 
Block-based protocol that uses standard Ethernet networks. Ideal for environments that require high performance, flexibility, and cost-effective scaling. 

iSCSI is widely used for VMFS datastores and supports advanced ONTAP features, such as snapshots and cloning.

* *High Performance:* Offers high performance to deliver fast, efficient data transfer rates and low latency. Ideal for demanding enterprise applications and virtualized environments.

* *Ease of Management:* Simplifies storage management by using familiar IP-based tools and protocols.

* *Cost Effective:* Uses existing Ethernet infrastructure, reducing the need for specialized hardware and allowing organizations to achieve reliable and scalable storage solutions.

For more information on using iSCSI with NetApp storage systems, refer to https://docs.netapp.com/us-en/ontap/san-admin/san-host-provisioning-concept.html[SAN Provisioning with iSCSI].

.Fibre Channel (FC)
High-speed, low-latency protocol that uses dedicated FC networks. FC is preferred for mission-critical workloads that demand reliability, dedicated bandwidth, and robust error correction. It is commonly used for VMFS datastores in enterprise environments.

* *High Performance:* FC provides high-speed data transfer rates, making it ideal for applications requiring fast and reliable access to large amounts of data.

* *Low Latency:* Very low latency, which is crucial for performance-sensitive applications like databases and virtualized environments.

* *Reliability:* FC networks are known for their robustness and reliability, with features like built-in redundancy and error correction.

* *Dedicated Bandwidth:* FC provides dedicated bandwidth for storage traffic, reducing the risk of network congestion.

For more information on using Fibre Channel with NetApp storage systems, refer to https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html[SAN Provisioning with FC].

.NFS (Network File System)
File-based protocol that enables easy sharing and management of files across hosts. NFS is simple to set up and scales efficiently, making it suitable for virtualized workloads and environments that require flexible file access. 

NFS datastores are supported by ONTAP and vSphere for both management and workload domains.

* *Simplicity and ease of use:* NFS is straightforward to set up and manage, making it an excellent choice for environments that require quick and easy file sharing.

* *Scalability:* ONTAP's architecture allows NFS to scale efficiently, supporting growing data needs without significant changes to the infrastructure.

* *Flexibility:* NFS supports a wide range of applications and workloads, making it versatile for various use cases, including virtualized environments.

For more information, refer to the link:vmw-vvf-overview.html[NFS v3 Reference Guide for vSphere 8].

.NVMe/TCP
Modern protocol that delivers high performance and low latency over standard Ethernet networks using TCP/IP. NVMe/TCP is ideal for demanding applications and large-scale data operations, providing scalability and cost efficiency without requiring specialized hardware.

* *High Performance:* Delivers exceptional performance with low latency and high data transfer rates. This is crucial for demanding applications and large-scale data operations.

* *Scalability:* Supports scalable configurations, allowing IT administrators to expand their infrastructure seamlessly as data requirements grow.

* *Cost Effective:* Runs over standard Ethernet switches and is encapsulated inside TCP datagrams. No special equipment required to implement.

For more information on the benefits of NVMe, refer to https://www.netapp.com/data-storage/nvme/what-is-nvme/[What is NVME?].

== Use cases for adding supplemental storage
The following use cases demonstrate how to add supplemental storage to VCF management domains and Virtual Infrastructure (VI) workload domains using different protocols and configurations.

* link:vmw-vcf-mgmt-supplemental-iscsi.html[Management Domain with iSCSI]

* link:vmw-vcf-mgmt-supplemental-fc.html[Management Domain with FC]

* link:vmw-vcf-viwld-supp-iscsi-vvols.html[Virtual Infrastructure Workload Domain with vVols (iSCSI)]

* link:vmw-vcf-viwld-supp-nfs-vvols.html[Virtual Infrastructure Workload Domain with vVols (NFS)]

* link:vmw-vcf-viwld-supp-nvme.html[Virtual Infrastructure Workload Domain with NVMe/TCP]

* link:vmw-vcf-viwld-supp-fc.html[Virtual Infrastructure Workload Domain with FC]
