---
sidebar: sidebar
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs
summary:
---
= Use an NFS datastore on ONTAP as principal storage for VCF management domain
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this use case we outline the procedure to create a NFS datastore on ONTAP as the primary storage for VMware Cloud Foundation (VCF) management domain. This procedure summarizes the required components, configuration steps, and deployment process.

== Introduction

Where appropriate we will refer to external documentation for the steps that must be performed in vCenter, and reference those steps that are specific to the storage configuration portion.

If NFS 4.1 datastore needs to be used for Principal Storage or if converting an existing NFS-based vSphere environment with ONTAP, refer to link:vmw-vcf-mgmt-nfs.html[Converge vSphere Environment (NFS datastore) to VCF Management Domain].

[NOTE]
VCF release 5.2 introduced the the capability to convert an existing vSphere 8 environment to a VCF management domain or import as VCF VI workload domains. Prior to this release, VMware vSAN was the only option for principal storage for the VCF management domain. NSX controller VMs are better to deploy on FC-based VMFS datastore or use dual network switch to avoid single point of failure. If those options are not available, consider using vSAN to host those VMs.


[NOTE]
This solution is applicable for ONTAP platforms supporting NFS storage including NetApp AFF, AFX and FAS. 

== Prerequisites

The following components and configurations are used in this scenario:

* NetApp storage system with a storage virtual machine (SVM) configured to allow NFS traffic.
* Logical interface (LIF) has been created on the IP network that is to carry NFS traffic and is associated with the SVM.
* A vSphere cluster with at least 2 x vSphere hosts.
* NFS datastore mounted on one of the vSphere hosts with same NFS server and export path that will be used for the management domain. 

[NOTE]
When deploying a VCF Domain, VCF validates connectivity to the NFS Server. This is done using the management adapter on the vSphere hosts before any additional vmkernel adapter is added with the NFS IP address. Therefore, it is necessary to ensure that either 1) the management network is routable to the NFS Server, or 2) a LIF for the management network has been added to the SVM hosting the NFS datastore volume, to ensure that the validation can proceed.

* Ensure ONTAP NFS VAAI tool is installed on one of the vSphere hosts which can be selected as template for the cluster image.
* Deploy VCF Installer tool.

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html[VMware Cloud Foundation Documentation].

== Deployment Steps

=== Management Domain - Default Cluster

VCF Installer tool supports VMFS on FC, NFS v3, and vSAN datastores for the management domain. The following steps outline the procedure to deploy a management domain with an NFSv3-based datastore on ONTAP as the principal storage.

[NOTE]
Validate or adjust the nConnect value for the NFS datastore after deployment.

For more information on using an existing vSphere environment, refer to link:vmw-vcf-mgmt-nfs.html[Converge vSphere Environment (NFS datastore) to VCF Management Domain].

=== Management Domain - Additional Cluster

To Expand the management domain with an additional cluster, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html[Add an SDDC Cluster to a VCF Domain].

On High-level, the steps to add an additional cluster to the management domain are as follows:
* Ensure the hosts are commissioned and network pools are configured in vCenter.
* NFS datastore volume is provisioned on the ONTAP storage system and exported to the hosts in the additional cluster.
* Create new SDDC Cluster creation on the Management Domain on vCenter and follow the wizard to add the additional cluster to the management domain.

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html[VMware Cloud Foundation Documentation].

