---
sidebar: sidebar
permalink: vmware/vmw-dr-gs.html
keywords: vmware, getting, started, overview, netapp, console, disaster, recovery
summary: 
---
= Learn about disaster recovery of virtual machines using NetApp Disaster Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp Disaster Recovery automates the replication and recovery of VMware virtual machines using ONTAP storage. It supports recovery from on-premises setup to VMware Cloud on AWS with Amazon FSx for NetApp ONTAP or another on-premises VMware environment. 

== Introduction

Having a successful plan and combination of technologies ensures the protection of critical data, applications and VMs. The challenge with DR is determining the appropriate level of protection and associated costs. 

ONTAP arrays offer built-in replication to transfer volume data, and therefore the virtual machines residing on the designated datastore LUNs, from one site to another. NetApp Disaster Recovery integrates with vSphere and automates the entire workflow for seamless failover and failback in the event of disaster. 

For more information on NetApp Disaster Recovery, see link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-overview.html[Overview of NetApp Disaster Recovery^].

== Considerations

The most time-consuming parts of a DR failover in a VMware vSphere environment is the execution of the steps necessary to inventory, register, reconfigure, and power up VMs at the DR site. An ideal solution has both a low RPO (as measured in minutes) and a low RTO (measured in minutes to hours). One factor that is often overlooked in a DR solution is the ability to test the DR solution efficiently on a periodic interval. 

To architect a DR solution, keep the following factors in mind:

* The recovery time objective (RTO). The RTO is how quickly a business can recover from a disaster, or, more specifically, how long it takes to execute the recovery process to make business services available again.
* The recovery point objective (RPO). The RPO is how old the recovered data is after it has been made available, relative to the time that the disaster occurred.
* Scalability and adaptability. This factor includes the ability to grow storage resources incrementally as demand increases.

For more technical information on the available solutions, please see:

* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-nfs.html[DR using NetApp Disaster Recovery for NFS Datastores^]

* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-vmfs.html[DR using NetApp Disaster Recovery for VMFS Datastores^]

// NetApp Solutions restructuring (jul 2025) - renamed from vmware/vmw-getting-started-bluexp-disaster-recovery.adoc
