---
sidebar: sidebar
permalink: vmware/vmw-getting-started-otv.html
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools
summary: 
---

= Learn about managing virtual machines using ONTAP tools for VMware vSphere
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere streamlines lifecycle management for VMs using NetApp storage. Administrators can manage storage directly from the vCenter Server, simplifying operations and enhancing scalability. Key components like the vSphere Client plug-in, VASA Provider, and Storage Replication Adapter (SRA) optimize provisioning, performance monitoring, and disaster recovery.

== Introduction

It enables  administrators to manage the storage within the vCenter Server directly and simplify the storage and data management for VMware environments. The VMware vSphere Client plug-in tool is designed to integrate plug-in functionality into the vSphere Client without the need to run inside vCenter Server. This provides plug-in isolation and enables scale-out of plug-ins that operate in large vSphere environments.
 
== ONTAP Tools Components

* *vSphere Client plug-in* The plug-in includes the interface integrated with the vSphere client where you can add storage controllers, provision datastores, monitor performance of datastores, and view and update ESXi host settings. In ONTAP tools 9.x, this component is called the Virtual Storage Console (VSC).

* *VASA Provider* The VMware vSphere APIs for Storage Awareness (VASA) Provider for ONTAP send information about storage used by VMware vSphere to the vCenter Server, enabling provisioning of VMware Virtual Volumes (vVols) datastores, creation and use of storage capability profiles, compliance verification, and performance monitoring.

* *Storage Replication Adapter (SRA)* When enabled and used with VMware Site Recovery Manager (SRM), SRA facilitates the recovery of vCenter Server datastores and virtual machines in the event of a failure, allowing configuration of protected sites and recovery sites for disaster recovery.

For more information, see the ONTAP tools for VMware vSphere documentation for your version:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html[ONTAP tools for VMware vSphere 10.x documentation^] (latest release)
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html[ONTAP tools for VMware vSphere 9.x documentation^]

// NetApp Solutions restructuring (jul 2025) - renamed from vmware/vmw-getting-started-ontap-tools-for-vmware.adoc
