---
sidebar: sidebar
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10
summary: "Review the requirements for converging a vSphere cluster with NetApp ONTAP NFS datastores to a VMware Cloud Foundation management domain."
---
= Deployment requirements for converging vCenter server instance to VCF management domain using NFS datastores
:icons: font
:imagesdir: ../media/

[.lead]
Review the requirements for converging a vSphere cluster with NetApp ONTAP NFS datastores to a VMware Cloud Foundation management domain.

The convergence process requires an AFF or AFX storage system, SVMs and LIFs for NFS traffic, NFS VLANs on switches, a vSphere cluster with vSphere hosts and vCenter, and dedicated network segment for vMotion.

== Infrastructure requirements
Make sure the following components and configurations are in place.

* NetApp AFF or AFX storage system with a storage virtual machine (SVM) configured to allow NFS traffic.
* Logical interface (LIF) created on the IP network to carry NFS traffic and associated with the SVM.
* A vSphere cluster with at least 2 x vSphere hosts and a vCenter appliance co-located on the cluster.
* Distributed port group configured for vMotion and NFS storage traffic on the VLANs or network segments established for this purpose.
* VCF Installer tool for converging the vCenter to the VCF management domain.
* Prerequisites for ONTAP tools.
+
For complete information about prerequisites for ONTAP tools, refer to https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements[Prerequisites for ONTAP tools for VMware vSphere deployment].
+
ONTAP tools for VMware vSphere can be installed in either HA or non-HA configurations. 

== Additional resources
* For supported storage and other considerations for converging vSphere to VCF, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html[Supported and Not Supported Configurations to Converge to VCF].

* For information about configuring ONTAP storage systems, refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 documentation].
* For information on configuring VCF, refer to the link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html[VMware Cloud Foundation 9.1 documentation].


== What's next?
After you've reviewed the deployment requirements, link:vmw-vcf-mgmt-nfs-deploy.html[deploy ONTAP tools and provision the NFS datastore].
