---
sidebar: sidebar
permalink: vmware/vmw-vcf-mgmt-vmfs-converge.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, aff, all-flash, fc, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10
summary: "Converge an existing vSphere cluster to a VCF management domain using the VCF Installer Tool. You'll validate the vCenter appliance, deploy the VCF Installer, reuse existing components and install new ones to complete the VCF management domain."
---
= Converge vSphere cluster to VCF management domain using the VCF Installer Tool
:icons: font
:imagesdir: ../media/

[.lead]
Converge an existing vSphere cluster to a VCF management domain using the VCF Installer Tool. You'll validate the vCenter appliance, deploy the VCF Installer, reuse existing components and install new ones to complete the VCF management domain.

Based on the components that are already deployed in your environment, the VCF Installer Tool will determine which components can be reused and which components need to be installed. The VCF Installer Tool will also validate the existing vCenter appliance and ensure that it meets the requirements for convergence.

Follow the steps documented at https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-.html[Converging your existing vSphere infrastructure to a VCF management domain] to complete the convergence process.

https://vmware.github.io/vcf-upgrade-planner/[VCF Upgrade Planning Tool] provides the high-level steps to complete the convergence process based on the inputs you provide.