---
sidebar: sidebar
permalink: vmware/vmw-vcf-viwld-principal-fc.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc
summary:
---
= Use an FC-based VMFS datastore on ONTAP as principal storage for a VCF workload domain
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this use case we outline the procedure to set up a Fibre Channel (FC) VMFS datastore on ONTAP as the primary storage solution for a VMware Cloud Foundation (VCF) workload domain. This procedure summarizes the required components, configuration steps, and deployment process.

== Benefits of Fibre Channel

*High Performance:* FC provides high-speed data transfer rates, making it ideal for applications requiring fast and reliable access to large amounts of data.

*Low Latency:* Very low latency, which is crucial for performance-sensitive applications like databases and virtualized environments.

*Reliability:* FC networks are known for their robustness and reliability, with features like built-in redundancy and error correction.

*Dedicated Bandwidth:* FC provides dedicated bandwidth for storage traffic, reducing the risk of network congestion.

For more information on using Fibre Channel with NetApp storage systems, refer to https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html[SAN Provisioning with FC].

== Scenario Overview

This scenario covers the following high level steps:

* Create a storage virtual machine (SVM) with logical interfaces (LIFs) for FC traffic.
* Collect WWPN information of hosts to be deployed and create corresponding initiator groups on the ONTAP storage system.
* Create an FC volume on the ONTAP storage system.
* Map initiator groups to FC volume created.
* Utilize single initiator-target zoning on FC switches. Create one zone for each initiator (single initiator zone).
** For each zone, include a target that is the ONTAP FC logical interface (WWPN) for the SVMs. There should be at least two logical interfaces per node per SVM. Do not use the WWPN of the physical ports.
* Create a Network Pool for vMotion traffic in vCenter.
* Commission hosts in vCenter for use in a Workload Domain.
* Deploy a Workload Domain in VCF Ops using an VMFS on FC datastore as principal storage.

[NOTE]
This solution is applicable for ONTAP platforms supporting FC storage including NetApp ASAr2, AFF and FAS.

== Prerequisites

The following components and configurations are used in this scenario:

* An ONTAP AFF, ASA, or FAS storage system with FC ports connected to FC switches.
* SVM created with FC lifs.
* vSphere with FC HBAs connected to FC switches.
* Single initiator-target zoning is configured on FC switches.
* Ensure SVM multipathing policy is set to active-active.

[NOTE]
NetApp recommends multipath for FC LUNs. 

== Deployment Steps



=== VCF Workload Domain - Default Cluster

After the management domain is up and running, VCF Workload domain can be created:

* Using VCF Ops UI. The vSphere hosts are commissioned in vCenter and network pool is configured. Use System Manager or ONTAP API to deploy LUN to vSphere hosts.

* Import an existing vSphere environment as new workload domain. ONTAP tools for VMware vSphere or System Manager or ONTAP API can be used to deploy the VMFS datastore to vSphere cluster.

=== VCF Workload Domain - Additional Cluster

To Expand the workload domain with an additional cluster, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html[Add an SDDC Cluster to a VCF Domain].

On a high level, the steps to add an additional cluster to the workload domain are as follows:
* Ensure the hosts are commissioned and network pools are configured in vCenter.
* LUN is provisioned on the ONTAP storage system and presented to the hosts in the additional cluster.
* Create new SDDC Cluster creation on the Workload Domain on vCenter and follow the wizard to add the additional cluster to the workload domain.

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html[VMware Cloud Foundation Documentation].